[project]
name = "tfl-status"
version = "0.0.2"
description = "A package to monitor the status updates of the TFL transport lines."
authors = ["Kia Sambrook <kiasambrook.co.uk>"]

[project.dependencies]
requests = "^2.32.3"
nicegui = "^2.1"
requests-cache = "^1.2.1"